project:
  type: website

website:
  title: "Greg"
  navbar:
    left:
      - text: "Technical"
        href: technical/index.qmd
      - text: "Philosophy"
        href: philosophy/index.qmd
      - text: "Finance & Economics"
        href: finance/index.qmd
  comments:
    hypothesis:
      theme: clean
      openSidebar: false

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true